# Generated by Django 6.1 on 2026-08-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='details',
            field=models.CharField(default='Not provided', max_length=100),
            preserve_default=False,
        ),
    ]
